// NICE Digital Health Technologies Guidance (HTG) list — v2 schema
// HTG refs normalised: "HTG 779.00" → "HTG779"
// conditionArea and subArea are kept as separate fields for richer search

export const ACRONYM_MAP = {
  // Condition areas
  'msk':    'musculoskeletal',
  'cvd':    'cardiovascular',
  'af':     'atrial fibrillation',
  'hf':     'heart failure',
  'chf':    'heart failure',
  'copd':   'chronic obstructive pulmonary disease',
  'adhd':   'attention deficit hyperactivity disorder',
  'oa':     'osteoarthritis',
  'lbp':    'low back pain',
  'mh':     'mental health',
  'pd':     "parkinson's disease",
  'ms':     'multiple sclerosis',
  // Technologies / methods
  'ai':     'artificial intelligence',
  'cr':     'cardiac rehabilitation',
  'pr':     'pulmonary rehabilitation',
  'cbt':    'cognitive behavioural therapy',
  'vr':     'virtual reality',
  'dht':    'digital health technology',
  'ecg':    'electrocardiogram',
  'ct':     'computed tomography',
  'cad':    'computer-aided detection',
  // Orgs / programmes
  'nice':   'national institute for health and care excellence',
  'nhs':    'national health service',
  'iapt':   'talking therapies',
}

export const NICE_HTG = [
  {
    htgRef: 'HTG779',
    title: 'Artificial intelligence (AI)-assisted echocardiography analysis and reporting to support the diagnosis and monitoring of heart failure: early-use assessment',
    conditionArea: 'Cardiovascular',
    subArea: 'heart failure',
    publishedDate: '19 May 2026',
    url: 'https://www.nice.org.uk/guidance/htg779',
  },
  {
    htgRef: 'HTG778',
    title: 'Digital technologies to support self-management of asthma: early-use assessment',
    conditionArea: 'Respiratory',
    subArea: 'asthma',
    publishedDate: '5 May 2026',
    url: 'https://www.nice.org.uk/guidance/htg778',
  },
  {
    htgRef: 'HTG776',
    title: 'Digital technologies for applying algorithms to spirometry to support asthma and COPD diagnosis in primary care and community diagnostic centres: early-use assessment',
    conditionArea: 'Respiratory',
    subArea: 'asthma / COPD',
    publishedDate: '2 April 2026',
    url: 'https://www.nice.org.uk/guidance/htg776',
  },
  {
    htgRef: 'HTG773',
    title: 'Artificial intelligence (AI) technologies to help detect or characterise colorectal polyps',
    conditionArea: 'Cancer / gastroenterology',
    subArea: 'colorectal polyps / colorectal cancer',
    publishedDate: '19 March 2026',
    url: 'https://www.nice.org.uk/guidance/htg773',
  },
  {
    htgRef: 'HTG769',
    title: 'Pulmonary artery pressure technologies for remote monitoring of chronic heart failure',
    conditionArea: 'Cardiovascular',
    subArea: 'heart failure',
    publishedDate: '5 February 2026',
    url: 'https://www.nice.org.uk/guidance/htg769',
  },
  {
    htgRef: 'HTG768',
    title: 'Digital self-help for eating disorders: early value assessment',
    conditionArea: 'Mental health',
    subArea: 'eating disorders',
    publishedDate: '22 January 2026',
    url: 'https://www.nice.org.uk/guidance/htg768',
  },
  {
    htgRef: 'HTG766',
    title: 'Digital technologies for managing mild to moderate symptoms of hip or knee osteoarthritis: early value assessment',
    conditionArea: 'Musculoskeletal',
    subArea: 'hip or knee osteoarthritis / arthritis',
    publishedDate: '22 January 2026',
    url: 'https://www.nice.org.uk/guidance/htg766',
  },
  {
    htgRef: 'HTG761',
    title: 'Digital platforms to support cardiac rehabilitation: early value assessment',
    conditionArea: 'Cardiovascular',
    subArea: 'cardiac rehabilitation',
    publishedDate: '4 December 2025',
    url: 'https://www.nice.org.uk/guidance/htg761',
  },
  {
    htgRef: 'HTG760',
    title: 'Artificial intelligence (AI) technologies to aid opportunistic detection of vertebral fragility fractures: early value assessment',
    conditionArea: 'Osteoporosis / fragility fractures',
    subArea: 'clinically MSK-adjacent',
    publishedDate: '14 October 2025',
    url: 'https://www.nice.org.uk/guidance/htg760',
  },
  {
    htgRef: 'HTG756',
    title: 'Digital front door technologies to gather service user information for NHS Talking Therapies for anxiety and depression assessments: early value assessment',
    conditionArea: 'Mental health',
    subArea: 'anxiety and depression / NHS Talking Therapies',
    publishedDate: '24 July 2025',
    url: 'https://www.nice.org.uk/guidance/htg756',
  },
  {
    htgRef: 'HTG748',
    title: 'Digital therapy for chronic tic disorders and Tourette syndrome: early value assessment',
    conditionArea: 'Mental health – neurodevelopmental',
    subArea: 'chronic tic disorders and Tourette syndrome',
    publishedDate: '7 May 2025',
    url: 'https://www.nice.org.uk/guidance/htg748',
  },
  {
    htgRef: 'HTG746',
    title: 'Artificial intelligence (AI) technologies for assessing and triaging skin lesions referred to the urgent suspected skin cancer pathway: early value assessment',
    conditionArea: 'Cancer / dermatology',
    subArea: 'skin cancer',
    publishedDate: '1 May 2025',
    url: 'https://www.nice.org.uk/guidance/htg746',
  },
  {
    htgRef: 'HTG739',
    title: 'Artificial intelligence (AI) technologies to help detect fractures on X-rays in urgent care: early value assessment',
    conditionArea: 'Musculoskeletal',
    subArea: 'fractures',
    publishedDate: '14 January 2025',
    url: 'https://www.nice.org.uk/guidance/htg739',
  },
  {
    htgRef: 'HTG736',
    title: 'Digital technologies to support self-management of COPD: early value assessment',
    conditionArea: 'Respiratory',
    subArea: 'COPD',
    publishedDate: '19 December 2024',
    url: 'https://www.nice.org.uk/guidance/htg736',
  },
  {
    htgRef: 'HTG730',
    title: 'Heart failure algorithms for remote monitoring in people with cardiac implantable electronic devices',
    conditionArea: 'Cardiovascular',
    subArea: 'heart failure',
    publishedDate: '24 October 2024',
    url: 'https://www.nice.org.uk/guidance/htg730',
  },
  {
    htgRef: 'HTG729',
    title: 'Digital technologies for assessing attention deficit hyperactivity disorder (ADHD)',
    conditionArea: 'Mental health / neurodevelopmental',
    subArea: 'ADHD',
    publishedDate: '21 October 2024',
    url: 'https://www.nice.org.uk/guidance/htg729',
  },
  {
    htgRef: 'HTG718',
    title: 'Digital technologies to deliver pulmonary rehabilitation programmes for adults with COPD: early value assessment',
    conditionArea: 'Respiratory',
    subArea: 'COPD / pulmonary rehabilitation',
    publishedDate: '30 April 2024',
    url: 'https://www.nice.org.uk/guidance/htg718',
  },
  {
    htgRef: 'HTG716',
    title: 'GaitSmart rehabilitation exercise programme for gait and mobility issues',
    conditionArea: 'Musculoskeletal',
    subArea: 'gait and mobility issues; includes hip / knee replacement research question',
    publishedDate: '3 April 2024',
    url: 'https://www.nice.org.uk/guidance/htg716',
  },
  {
    htgRef: 'HTG713',
    title: 'Digital health technologies to help manage symptoms of psychosis and prevent relapse in adults and young people: early value assessment',
    conditionArea: 'Mental health',
    subArea: 'psychosis and relapse prevention',
    publishedDate: '25 March 2024',
    url: 'https://www.nice.org.uk/guidance/htg713',
  },
  {
    htgRef: 'HTG712',
    title: 'Digital technologies for managing non-specific low back pain: early value assessment',
    conditionArea: 'Musculoskeletal',
    subArea: 'low back pain',
    publishedDate: '5 March 2024',
    url: 'https://www.nice.org.uk/guidance/htg712',
  },
  {
    htgRef: 'HTG708',
    title: 'Artificial intelligence (AI)-derived software to help clinical decision making in stroke',
    conditionArea: 'Cardiovascular / neurology',
    subArea: 'stroke',
    publishedDate: '23 January 2024',
    url: 'https://www.nice.org.uk/guidance/htg708',
  },
  {
    htgRef: 'HTG701',
    title: 'Virtual reality technologies for treating agoraphobia or agoraphobic avoidance: early value assessment',
    conditionArea: 'Mental health',
    subArea: 'anxiety / agoraphobia',
    publishedDate: '15 November 2023',
    url: 'https://www.nice.org.uk/guidance/htg701',
  },
  {
    htgRef: 'HTG700',
    title: 'Digital technologies for delivering multidisciplinary weight-management services: early value assessment',
    conditionArea: 'Obesity / metabolic health',
    subArea: 'weight management',
    publishedDate: '26 October 2023',
    url: 'https://www.nice.org.uk/guidance/htg700',
  },
  {
    htgRef: 'HTG697',
    title: 'Virtual ward platform technologies for acute respiratory infections: early value assessment',
    conditionArea: 'Respiratory',
    subArea: 'acute respiratory infections',
    publishedDate: '12 October 2023',
    url: 'https://www.nice.org.uk/guidance/htg697',
  },
  {
    htgRef: 'HTG696',
    title: 'Artificial intelligence (AI)-derived software to analyse chest X-rays for suspected lung cancer in primary care referrals: early value assessment',
    conditionArea: 'Cancer / respiratory',
    subArea: 'lung cancer',
    publishedDate: '28 September 2023',
    url: 'https://www.nice.org.uk/guidance/htg696',
  },
  {
    htgRef: 'HTG694',
    title: 'KardiaMobile 6L for measuring cardiac QT interval in adults having antipsychotic medication: early value assessment',
    conditionArea: 'Mental health with cardiovascular monitoring',
    subArea: 'QT monitoring during antipsychotic treatment',
    publishedDate: '26 September 2023',
    url: 'https://www.nice.org.uk/guidance/htg694',
  },
  {
    htgRef: 'HTG687',
    title: 'Artificial intelligence (AI)-derived computer-aided detection (CAD) software for detecting and measuring lung nodules in CT scan images',
    conditionArea: 'Cancer / respiratory',
    subArea: 'lung nodules / lung cancer',
    publishedDate: '5 July 2023',
    url: 'https://www.nice.org.uk/guidance/htg687',
  },
  {
    htgRef: 'HTG676',
    title: 'Digitally enabled therapies for adults with anxiety disorders: early value assessment',
    conditionArea: 'Mental health',
    subArea: 'anxiety disorders',
    publishedDate: '16 May 2023',
    url: 'https://www.nice.org.uk/guidance/htg676',
  },
  {
    htgRef: 'HTG675',
    title: 'Digitally enabled therapies for adults with depression: early value assessment',
    conditionArea: 'Mental health',
    subArea: 'depression',
    publishedDate: '16 May 2023',
    url: 'https://www.nice.org.uk/guidance/htg675',
  },
  {
    htgRef: 'HTG664',
    title: 'ProKnow cloud-based system for radiotherapy data storage, communication and management: early value assessment',
    conditionArea: 'Cancer / radiotherapy services',
    subArea: 'radiotherapy data management',
    publishedDate: '28 March 2023',
    url: 'https://www.nice.org.uk/guidance/htg664',
  },
  {
    htgRef: 'HTG660',
    title: 'Guided self-help digital cognitive behavioural therapy for children and young people with mild to moderate symptoms of anxiety or low mood: early value assessment',
    conditionArea: 'Mental health',
    subArea: 'anxiety / low mood in children and young people',
    publishedDate: '8 February 2023',
    url: 'https://www.nice.org.uk/guidance/htg660',
  },
  {
    htgRef: 'HTG657',
    title: "Devices for remote monitoring of Parkinson's disease",
    conditionArea: 'Neurological',
    subArea: "Parkinson's disease",
    publishedDate: '25 January 2023',
    url: 'https://www.nice.org.uk/guidance/htg657',
  },
  {
    htgRef: 'HTG624',
    title: 'Sleepio to treat insomnia and insomnia symptoms',
    conditionArea: 'Sleep medicine',
    subArea: 'insomnia and insomnia symptoms',
    publishedDate: '20 May 2022',
    url: 'https://www.nice.org.uk/guidance/htg624',
  },
  {
    htgRef: 'HTG606',
    title: 'KardiaMobile for detecting atrial fibrillation',
    conditionArea: 'Cardiovascular',
    subArea: 'atrial fibrillation',
    publishedDate: '6 January 2022',
    url: 'https://www.nice.org.uk/guidance/htg606',
  },
  {
    htgRef: 'HTG571',
    title: 'QAngio XA 3D QFR and CAAS vFFR imaging software for assessing coronary stenosis during invasive coronary angiography',
    conditionArea: 'Cardiovascular',
    subArea: 'coronary stenosis',
    publishedDate: '17 March 2021',
    url: 'https://www.nice.org.uk/guidance/htg571',
  },
  {
    htgRef: 'HTG562',
    title: 'Zio XT for detecting cardiac arrhythmias',
    conditionArea: 'Cardiovascular',
    subArea: 'cardiac arrhythmias',
    publishedDate: '1 December 2020',
    url: 'https://www.nice.org.uk/guidance/htg562',
  },
  {
    htgRef: 'HTG553',
    title: 'Implantable cardiac monitors to detect atrial fibrillation after cryptogenic stroke',
    conditionArea: 'Cardiovascular / stroke',
    subArea: 'AF after cryptogenic stroke',
    publishedDate: '2 September 2020',
    url: 'https://www.nice.org.uk/guidance/htg553',
  },
  {
    htgRef: 'HTG508',
    title: 'Lead-I ECG devices for detecting symptomatic atrial fibrillation using single time point testing in primary care',
    conditionArea: 'Cardiovascular',
    subArea: 'symptomatic atrial fibrillation',
    publishedDate: '8 May 2019',
    url: 'https://www.nice.org.uk/guidance/htg508',
  },
  {
    htgRef: 'HTG465',
    title: 'Thopaz+ portable digital system for managing chest drains',
    conditionArea: 'Thoracic surgery / respiratory',
    subArea: 'chest drain management',
    publishedDate: '21 March 2018',
    url: 'https://www.nice.org.uk/guidance/htg465',
  },
  {
    htgRef: 'HTG429',
    title: 'HeartFlow FFRCT for estimating fractional flow reserve from coronary CT angiography',
    conditionArea: 'Cardiovascular',
    subArea: 'coronary artery disease',
    publishedDate: '13 February 2017',
    url: 'https://www.nice.org.uk/guidance/htg429',
  },
  {
    htgRef: 'HTG353',
    title: 'Atrial fibrillation and heart valve disease: self-monitoring coagulation status using point-of-care coagulometers',
    conditionArea: 'Cardiovascular',
    subArea: 'AF / heart valve disease / anticoagulation monitoring',
    publishedDate: '24 September 2014',
    url: 'https://www.nice.org.uk/guidance/htg353',
  },
]

// Look up the NICE HTG reference for a stored pathway/condition name.
// Matches the pathway against entry titles (exact, case-insensitive) so that
// saved assessments — which store the pathway text but not always the ref —
// can still display their HTG number.
export function htgRefForPathway(pathway) {
  if (!pathway) return null
  const q = String(pathway).trim().toLowerCase()
  if (!q) return null
  const match = NICE_HTG.find(e => e.title.toLowerCase() === q)
  return match?.htgRef ?? null
}
